import Ember from 'ember';

export default Ember.Object.extend({
  init() { this.set('countryList', [
  {text: 'Afghanistan'                                 ,  country: 'Afghanistan'                                 , iso: 'AF',id: 'AF'},
  {text: 'Åland Islands'                               ,  country: 'Åland Islands'                               , iso: 'AX',id: 'AX'},
  {text: 'Albania'                                     ,  country: 'Albania'                                     , iso: 'AL',id: 'AL'},
  {text: 'Algeria'                                     ,  country: 'Algeria'                                     , iso: 'DZ',id: 'DZ'},
  {text: 'American Samoa'                              ,  country: 'American Samoa'                              , iso: 'AS',id: 'AS'},
  {text: 'Andorra'                                     ,  country: 'Andorra'                                     , iso: 'AD',id: 'AD'},
  {text: 'Angola'                                      ,  country: 'Angola'                                      , iso: 'AO',id: 'AO'},
  {text: 'Anguilla'                                    ,  country: 'Anguilla'                                    , iso: 'AI',id: 'AI'},
  {text: 'Antarctica'                                  ,  country: 'Antarctica'                                  , iso: 'AQ',id: 'AQ'},
  {text: 'Antigua and Barbuda'                         ,  country: 'Antigua and Barbuda'                         , iso: 'AG',id: 'AG'},
  {text: 'Argentina'                                   ,  country: 'Argentina'                                   , iso: 'AR',id: 'AR'},
  {text: 'Armenia'                                     ,  country: 'Armenia'                                     , iso: 'AM',id: 'AM'},
  {text: 'Aruba'                                       ,  country: 'Aruba'                                       , iso: 'AW',id: 'AW'},
  {text: 'Australia'                                   ,  country: 'Australia'                                   , iso: 'AU',id: 'AU'},
  {text: 'Austria'                                     ,  country: 'Austria'                                     , iso: 'AT',id: 'AT'},
  {text: 'Azerbaijan'                                  ,  country: 'Azerbaijan'                                  , iso: 'AZ',id: 'AZ'},
  {text: 'Bahamas'                                     ,  country: 'Bahamas'                                     , iso: 'BS',id: 'BS'},
  {text: 'Bahrain'                                     ,  country: 'Bahrain'                                     , iso: 'BH',id: 'BH'},
  {text: 'Bangladesh'                                  ,  country: 'Bangladesh'                                  , iso: 'BD',id: 'BD'},
  {text: 'Barbados'                                    ,  country: 'Barbados'                                    , iso: 'BB',id: 'BB'},
  {text: 'Belarus'                                     ,  country: 'Belarus'                                     , iso: 'BY',id: 'BY'},
  {text: 'Belgium'                                     ,  country: 'Belgium'                                     , iso: 'BE',id: 'BE'},
  {text: 'Belize'                                      ,  country: 'Belize'                                      , iso: 'BZ',id: 'BZ'},
  {text: 'Benin'                                       ,  country: 'Benin'                                       , iso: 'BJ',id: 'BJ'},
  {text: 'Bermuda'                                     ,  country: 'Bermuda'                                     , iso: 'BM',id: 'BM'},
  {text: 'Bhutan'                                      ,  country: 'Bhutan'                                      , iso: 'BT',id: 'BT'},
  {text: 'Bolivia, Plurinational State of'             ,  country: 'Bolivia, Plurinational State of'             , iso: 'BO',id: 'BO'},
  {text: 'Bonaire, Sint Eustatius and Saba'            ,  country: 'Bonaire, Sint Eustatius and Saba'            , iso: 'BQ',id: 'BQ'},
  {text: 'Bosnia and Herzegovina'                      ,  country: 'Bosnia and Herzegovina'                      , iso: 'BA',id: 'BA'},
  {text: 'Botswana'                                    ,  country: 'Botswana'                                    , iso: 'BW',id: 'BW'},
  {text: 'Bouvet Island'                               ,  country: 'Bouvet Island'                               , iso: 'BV',id: 'BV'},
  {text: 'Brazil'                                      ,  country: 'Brazil'                                      , iso: 'BR',id: 'BR'},
  {text: 'British Indian Ocean Territory'              ,  country: 'British Indian Ocean Territory'              , iso: 'IO',id: 'IO'},
  {text: 'Brunei Darussalam'                           ,  country: 'Brunei Darussalam'                           , iso: 'BN',id: 'BN'},
  {text: 'Bulgaria'                                    ,  country: 'Bulgaria'                                    , iso: 'BG',id: 'BG'},
  {text: 'Burkina Faso'                                ,  country: 'Burkina Faso'                                , iso: 'BF',id: 'BF'},
  {text: 'Burundi'                                     ,  country: 'Burundi'                                     , iso: 'BI',id: 'BI'},
  {text: 'Cambodia'                                    ,  country: 'Cambodia'                                    , iso: 'KH',id: 'KH'},
  {text: 'Cameroon'                                    ,  country: 'Cameroon'                                    , iso: 'CM',id: 'CM'},
  {text: 'Canada'                                      ,  country: 'Canada'                                      , iso: 'CA',id: 'CA'},
  {text: 'Cape Verde'                                  ,  country: 'Cape Verde'                                  , iso: 'CV',id: 'CV'},
  {text: 'Cayman Islands'                              ,  country: 'Cayman Islands'                              , iso: 'KY',id: 'KY'},
  {text: 'Central African Republic'                    ,  country: 'Central African Republic'                    , iso: 'CF',id: 'CF'},
  {text: 'Chad'                                        ,  country: 'Chad'                                        , iso: 'TD',id: 'TD'},
  {text: 'Chile'                                       ,  country: 'Chile'                                       , iso: 'CL',id: 'CL'},
  {text: 'China'                                       ,  country: 'China'                                       , iso: 'CN',id: 'CN'},
  {text: 'Christmas Island'                            ,  country: 'Christmas Island'                            , iso: 'CX',id: 'CX'},
  {text: 'Cocos (Keeling) Islands'                     ,  country: 'Cocos (Keeling) Islands'                     , iso: 'CC',id: 'CC'},
  {text: 'Colombia'                                    ,  country: 'Colombia'                                    , iso: 'CO',id: 'CO'},
  {text: 'Comoros'                                     ,  country: 'Comoros'                                     , iso: 'KM',id: 'KM'},
  {text: 'Congo'                                       ,  country: 'Congo'                                       , iso: 'CG',id: 'CG'},
  {text: 'Congo, the Democratic Republic of the'       ,  country: 'Congo, the Democratic Republic of the'       , iso: 'CD',id: 'CD'},
  {text: 'Cook Islands'                                ,  country: 'Cook Islands'                                , iso: 'CK',id: 'CK'},
  {text: 'Costa Rica'                                  ,  country: 'Costa Rica'                                  , iso: 'CR',id: 'CR'},
  {text: 'Côte d\'Ivoire'                              ,  country: 'Côte d\'Ivoire'                              , iso: 'CI',id: 'CI'},
  {text: 'Croatia'                                     ,  country: 'Croatia'                                     , iso: 'HR',id: 'HR'},
  {text: 'Cuba'                                        ,  country: 'Cuba'                                        , iso: 'CU',id: 'CU'},
  {text: 'Curaçao'                                     ,  country: 'Curaçao'                                     , iso: 'CW',id: 'CW'},
  {text: 'Cyprus'                                      ,  country: 'Cyprus'                                      , iso: 'CY',id: 'CY'},
  {text: 'Czech Republic'                              ,  country: 'Czech Republic'                              , iso: 'CZ',id: 'CZ'},
  {text: 'Denmark'                                     ,  country: 'Denmark'                                     , iso: 'DK',id: 'DK'},
  {text: 'Djibouti'                                    ,  country: 'Djibouti'                                    , iso: 'DJ',id: 'DJ'},
  {text: 'Dominica'                                    ,  country: 'Dominica'                                    , iso: 'DM',id: 'DM'},
  {text: 'Dominican Republic'                          ,  country: 'Dominican Republic'                          , iso: 'DO',id: 'DO'},
  {text: 'Ecuador'                                     ,  country: 'Ecuador'                                     , iso: 'EC',id: 'EC'},
  {text: 'Egypt'                                       ,  country: 'Egypt'                                       , iso: 'EG',id: 'EG'},
  {text: 'El Salvador'                                 ,  country: 'El Salvador'                                 , iso: 'SV',id: 'SV'},
  {text: 'Equatorial Guinea'                           ,  country: 'Equatorial Guinea'                           , iso: 'GQ',id: 'GQ'},
  {text: 'Eritrea'                                     ,  country: 'Eritrea'                                     , iso: 'ER',id: 'ER'},
  {text: 'Estonia'                                     ,  country: 'Estonia'                                     , iso: 'EE',id: 'EE'},
  {text: 'Ethiopia'                                    ,  country: 'Ethiopia'                                    , iso: 'ET',id: 'ET'},
  {text: 'Falkland Islands (Malvinas)'                 ,  country: 'Falkland Islands (Malvinas)'                 , iso: 'FK',id: 'FK'},
  {text: 'Faroe Islands'                               ,  country: 'Faroe Islands'                               , iso: 'FO',id: 'FO'},
  {text: 'Fiji'                                        ,  country: 'Fiji'                                        , iso: 'FJ',id: 'FJ'},
  {text: 'Finland'                                     ,  country: 'Finland'                                     , iso: 'FI',id: 'FI'},
  {text: 'France'                                      ,  country: 'France'                                      , iso: 'FR',id: 'FR'},
  {text: 'French Guiana'                               ,  country: 'French Guiana'                               , iso: 'GF',id: 'GF'},
  {text: 'French Polynesia'                            ,  country: 'French Polynesia'                            , iso: 'PF',id: 'PF'},
  {text: 'French Southern Territories'                 ,  country: 'French Southern Territories'                 , iso: 'TF',id: 'TF'},
  {text: 'Gabon'                                       ,  country: 'Gabon'                                       , iso: 'GA',id: 'GA'},
  {text: 'Gambia'                                      ,  country: 'Gambia'                                      , iso: 'GM',id: 'GM'},
  {text: 'Georgia'                                     ,  country: 'Georgia'                                     , iso: 'GE',id: 'GE'},
  {text: 'Germany'                                     ,  country: 'Germany'                                     , iso: 'DE',id: 'DE'},
  {text: 'Ghana'                                       ,  country: 'Ghana'                                       , iso: 'GH',id: 'GH'},
  {text: 'Gibraltar'                                   ,  country: 'Gibraltar'                                   , iso: 'GI',id: 'GI'},
  {text: 'Greece'                                      ,  country: 'Greece'                                      , iso: 'GR',id: 'GR'},
  {text: 'Greenland'                                   ,  country: 'Greenland'                                   , iso: 'GL',id: 'GL'},
  {text: 'Grenada'                                     ,  country: 'Grenada'                                     , iso: 'GD',id: 'GD'},
  {text: 'Guadeloupe'                                  ,  country: 'Guadeloupe'                                  , iso: 'GP',id: 'GP'},
  {text: 'Guam'                                        ,  country: 'Guam'                                        , iso: 'GU',id: 'GU'},
  {text: 'Guatemala'                                   ,  country: 'Guatemala'                                   , iso: 'GT',id: 'GT'},
  {text: 'Guernsey'                                    ,  country: 'Guernsey'                                    , iso: 'GG',id: 'GG'},
  {text: 'Guinea'                                      ,  country: 'Guinea'                                      , iso: 'GN',id: 'GN'},
  {text: 'Guinea-Bissau'                               ,  country: 'Guinea-Bissau'                               , iso: 'GW',id: 'GW'},
  {text: 'Guyana'                                      ,  country: 'Guyana'                                      , iso: 'GY',id: 'GY'},
  {text: 'Haiti'                                       ,  country: 'Haiti'                                       , iso: 'HT',id: 'HT'},
  {text: 'Heard Island and McDonald Islands'           ,  country: 'Heard Island and McDonald Islands'           , iso: 'HM',id: 'HM'},
  {text: 'Holy See (Vatican City State)'               ,  country: 'Holy See (Vatican City State)'               , iso: 'VA',id: 'VA'},
  {text: 'Honduras'                                    ,  country: 'Honduras'                                    , iso: 'HN',id: 'HN'},
  {text: 'Hong Kong'                                   ,  country: 'Hong Kong'                                   , iso: 'HK',id: 'HK'},
  {text: 'Hungary'                                     ,  country: 'Hungary'                                     , iso: 'HU',id: 'HU'},
  {text: 'Iceland'                                     ,  country: 'Iceland'                                     , iso: 'IS',id: 'IS'},
  {text: 'India'                                       ,  country: 'India'                                       , iso: 'IN',id: 'IN'},
  {text: 'Indonesia'                                   ,  country: 'Indonesia'                                   , iso: 'ID',id: 'ID'},
  {text: 'Iran, Islamic Republic of'                   ,  country: 'Iran, Islamic Republic of'                   , iso: 'IR',id: 'IR'},
  {text: 'Iraq'                                        ,  country: 'Iraq'                                        , iso: 'IQ',id: 'IQ'},
  {text: 'Ireland'                                     ,  country: 'Ireland'                                     , iso: 'IE',id: 'IE'},
  {text: 'Isle of Man'                                 ,  country: 'Isle of Man'                                 , iso: 'IM',id: 'IM'},
  {text: 'Israel'                                      ,  country: 'Israel'                                      , iso: 'IL',id: 'IL'},
  {text: 'Italy'                                       ,  country: 'Italy'                                       , iso: 'IT',id: 'IT'},
  {text: 'Jamaica'                                     ,  country: 'Jamaica'                                     , iso: 'JM',id: 'JM'},
  {text: 'Japan'                                       ,  country: 'Japan'                                       , iso: 'JP',id: 'JP'},
  {text: 'Jersey'                                      ,  country: 'Jersey'                                      , iso: 'JE',id: 'JE'},
  {text: 'Jordan'                                      ,  country: 'Jordan'                                      , iso: 'JO',id: 'JO'},
  {text: 'Kazakhstan'                                  ,  country: 'Kazakhstan'                                  , iso: 'KZ',id: 'KZ'},
  {text: 'Kenya'                                       ,  country: 'Kenya'                                       , iso: 'KE',id: 'KE'},
  {text: 'Kiribati'                                    ,  country: 'Kiribati'                                    , iso: 'KI',id: 'KI'},
  {text: 'Korea, Democratic People\'s Republic of'     ,  country: 'Korea, Democratic People\'s Republic of'     , iso: 'KP',id: 'KP'},
  {text: 'Korea, Republic of'                          ,  country: 'Korea, Republic of'                          , iso: 'KR',id: 'KR'},
  {text: 'Kuwait'                                      ,  country: 'Kuwait'                                      , iso: 'KW',id: 'KW'},
  {text: 'Kyrgyzstan'                                  ,  country: 'Kyrgyzstan'                                  , iso: 'KG',id: 'KG'},
  {text: 'Lao People\'s Democratic Republic'           ,  country: 'Lao People\'s Democratic Republic'           , iso: 'LA',id: 'LA'},
  {text: 'Latvia'                                      ,  country: 'Latvia'                                      , iso: 'LV',id: 'LV'},
  {text: 'Lebanon'                                     ,  country: 'Lebanon'                                     , iso: 'LB',id: 'LB'},
  {text: 'Lesotho'                                     ,  country: 'Lesotho'                                     , iso: 'LS',id: 'LS'},
  {text: 'Liberia'                                     ,  country: 'Liberia'                                     , iso: 'LR',id: 'LR'},
  {text: 'Libya'                                       ,  country: 'Libya'                                       , iso: 'LY',id: 'LY'},
  {text: 'Liechtenstein'                               ,  country: 'Liechtenstein'                               , iso: 'LI',id: 'LI'},
  {text: 'Lithuania'                                   ,  country: 'Lithuania'                                   , iso: 'LT',id: 'LT'},
  {text: 'Luxembourg'                                  ,  country: 'Luxembourg'                                  , iso: 'LU',id: 'LU'},
  {text: 'Macao'                                       ,  country: 'Macao'                                       , iso: 'MO',id: 'MO'},
  {text: 'Macedonia, the Former Yugoslav Republic of'  ,  country: 'Macedonia, the Former Yugoslav Republic of'  , iso: 'MK',id: 'MK'},
  {text: 'Madagascar'                                  ,  country: 'Madagascar'                                  , iso: 'MG',id: 'MG'},
  {text: 'Malawi'                                      ,  country: 'Malawi'                                      , iso: 'MW',id: 'MW'},
  {text: 'Malaysia'                                    ,  country: 'Malaysia'                                    , iso: 'MY',id: 'MY'},
  {text: 'Maldives'                                    ,  country: 'Maldives'                                    , iso: 'MV',id: 'MV'},
  {text: 'Mali'                                        ,  country: 'Mali'                                        , iso: 'ML',id: 'ML'},
  {text: 'Malta'                                       ,  country: 'Malta'                                       , iso: 'MT',id: 'MT'},
  {text: 'Marshall Islands'                            ,  country: 'Marshall Islands'                            , iso: 'MH',id: 'MH'},
  {text: 'Martinique'                                  ,  country: 'Martinique'                                  , iso: 'MQ',id: 'MQ'},
  {text: 'Mauritania'                                  ,  country: 'Mauritania'                                  , iso: 'MR',id: 'MR'},
  {text: 'Mauritius'                                   ,  country: 'Mauritius'                                   , iso: 'MU',id: 'MU'},
  {text: 'Mayotte'                                     ,  country: 'Mayotte'                                     , iso: 'YT',id: 'YT'},
  {text: 'Mexico'                                      ,  country: 'Mexico'                                      , iso: 'MX',id: 'MX'},
  {text: 'Micronesia, Federated States of'             ,  country: 'Micronesia, Federated States of'             , iso: 'FM',id: 'FM'},
  {text: 'Moldova, Republic of'                        ,  country: 'Moldova, Republic of'                        , iso: 'MD',id: 'MD'},
  {text: 'Monaco'                                      ,  country: 'Monaco'                                      , iso: 'MC',id: 'MC'},
  {text: 'Mongolia'                                    ,  country: 'Mongolia'                                    , iso: 'MN',id: 'MN'},
  {text: 'Montenegro'                                  ,  country: 'Montenegro'                                  , iso: 'ME',id: 'ME'},
  {text: 'Montserrat'                                  ,  country: 'Montserrat'                                  , iso: 'MS',id: 'MS'},
  {text: 'Morocco'                                     ,  country: 'Morocco'                                     , iso: 'MA',id: 'MA'},
  {text: 'Mozambique'                                  ,  country: 'Mozambique'                                  , iso: 'MZ',id: 'MZ'},
  {text: 'Myanmar'                                     ,  country: 'Myanmar'                                     , iso: 'MM',id: 'MM'},
  {text: 'Namibia'                                     ,  country: 'Namibia'                                     , iso: 'NA',id: 'NA'},
  {text: 'Nauru'                                       ,  country: 'Nauru'                                       , iso: 'NR',id: 'NR'},
  {text: 'Nepal'                                       ,  country: 'Nepal'                                       , iso: 'NP',id: 'NP'},
  {text: 'Netherlands'                                 ,  country: 'Netherlands'                                 , iso: 'NL',id: 'NL'},
  {text: 'New Caledonia'                               ,  country: 'New Caledonia'                               , iso: 'NC',id: 'NC'},
  {text: 'New Zealand'                                 ,  country: 'New Zealand'                                 , iso: 'NZ',id: 'NZ'},
  {text: 'Nicaragua'                                   ,  country: 'Nicaragua'                                   , iso: 'NI',id: 'NI'},
  {text: 'Niger'                                       ,  country: 'Niger'                                       , iso: 'NE',id: 'NE'},
  {text: 'Nigeria'                                     ,  country: 'Nigeria'                                     , iso: 'NG',id: 'NG'},
  {text: 'Niue'                                        ,  country: 'Niue'                                        , iso: 'NU',id: 'NU'},
  {text: 'Norfolk Island'                              ,  country: 'Norfolk Island'                              , iso: 'NF',id: 'NF'},
  {text: 'Northern Mariana Islands'                    ,  country: 'Northern Mariana Islands'                    , iso: 'MP',id: 'MP'},
  {text: 'Norway'                                      ,  country: 'Norway'                                      , iso: 'NO',id: 'NO'},
  {text: 'Oman'                                        ,  country: 'Oman'                                        , iso: 'OM',id: 'OM'},
  {text: 'Pakistan'                                    ,  country: 'Pakistan'                                    , iso: 'PK',id: 'PK'},
  {text: 'Palau'                                       ,  country: 'Palau'                                       , iso: 'PW',id: 'PW'},
  {text: 'Palestine, State of'                         ,  country: 'Palestine, State of'                         , iso: 'PS',id: 'PS'},
  {text: 'Panama'                                      ,  country: 'Panama'                                      , iso: 'PA',id: 'PA'},
  {text: 'Papua New Guinea'                            ,  country: 'Papua New Guinea'                            , iso: 'PG',id: 'PG'},
  {text: 'Paraguay'                                    ,  country: 'Paraguay'                                    , iso: 'PY',id: 'PY'},
  {text: 'Peru'                                        ,  country: 'Peru'                                        , iso: 'PE',id: 'PE'},
  {text: 'Philippines'                                 ,  country: 'Philippines'                                 , iso: 'PH',id: 'PH'},
  {text: 'Pitcairn'                                    ,  country: 'Pitcairn'                                    , iso: 'PN',id: 'PN'},
  {text: 'Poland'                                      ,  country: 'Poland'                                      , iso: 'PL',id: 'PL'},
  {text: 'Portugal'                                    ,  country: 'Portugal'                                    , iso: 'PT',id: 'PT'},
  {text: 'Puerto Rico'                                 ,  country: 'Puerto Rico'                                 , iso: 'PR',id: 'PR'},
  {text: 'Qatar'                                       ,  country: 'Qatar'                                       , iso: 'QA',id: 'QA'},
  {text: 'Réunion'                                     ,  country: 'Réunion'                                     , iso: 'RE',id: 'RE'},
  {text: 'Romania'                                     ,  country: 'Romania'                                     , iso: 'RO',id: 'RO'},
  {text: 'Russian Federation'                          ,  country: 'Russian Federation'                          , iso: 'RU',id: 'RU'},
  {text: 'Rwanda'                                      ,  country: 'Rwanda'                                      , iso: 'RW',id: 'RW'},
  {text: 'Saint Barthélemy'                            ,  country: 'Saint Barthélemy'                            , iso: 'BL',id: 'BL'},
  {text: 'Saint Helena, Ascension and Tristan da Cunha',  country: 'Saint Helena, Ascension and Tristan da Cunha', iso: 'SH',id: 'SH'},
  {text: 'Saint Kitts and Nevis'                       ,  country: 'Saint Kitts and Nevis'                       , iso: 'KN',id: 'KN'},
  {text: 'Saint Lucia'                                 ,  country: 'Saint Lucia'                                 , iso: 'LC',id: 'LC'},
  {text: 'Saint Martin (French part)'                  ,  country: 'Saint Martin (French part)'                  , iso: 'MF',id: 'MF'},
  {text: 'Saint Pierre and Miquelon'                   ,  country: 'Saint Pierre and Miquelon'                   , iso: 'PM',id: 'PM'},
  {text: 'Saint Vincent and the Grenadines'            ,  country: 'Saint Vincent and the Grenadines'            , iso: 'VC',id: 'VC'},
  {text: 'Samoa'                                       ,  country: 'Samoa'                                       , iso: 'WS',id: 'WS'},
  {text: 'San Marino'                                  ,  country: 'San Marino'                                  , iso: 'SM',id: 'SM'},
  {text: 'Sao Tome and Principe'                       ,  country: 'Sao Tome and Principe'                       , iso: 'ST',id: 'ST'},
  {text: 'Saudi Arabia'                                ,  country: 'Saudi Arabia'                                , iso: 'SA',id: 'SA'},
  {text: 'Senegal'                                     ,  country: 'Senegal'                                     , iso: 'SN',id: 'SN'},
  {text: 'Serbia'                                      ,  country: 'Serbia'                                      , iso: 'RS',id: 'RS'},
  {text: 'Seychelles'                                  ,  country: 'Seychelles'                                  , iso: 'SC',id: 'SC'},
  {text: 'Sierra Leone'                                ,  country: 'Sierra Leone'                                , iso: 'SL',id: 'SL'},
  {text: 'Singapore'                                   ,  country: 'Singapore'                                   , iso: 'SG',id: 'SG'},
  {text: 'Sint Maarten (Dutch part)'                   ,  country: 'Sint Maarten (Dutch part)'                   , iso: 'SX',id: 'SX'},
  {text: 'Slovakia'                                    ,  country: 'Slovakia'                                    , iso: 'SK',id: 'SK'},
  {text: 'Slovenia'                                    ,  country: 'Slovenia'                                    , iso: 'SI',id: 'SI'},
  {text: 'Solomon Islands'                             ,  country: 'Solomon Islands'                             , iso: 'SB',id: 'SB'},
  {text: 'Somalia'                                     ,  country: 'Somalia'                                     , iso: 'SO',id: 'SO'},
  {text: 'South Africa'                                ,  country: 'South Africa'                                , iso: 'ZA',id: 'ZA'},
  {text: 'South Georgia and the South Sandwich Islands',  country: 'South Georgia and the South Sandwich Islands', iso: 'GS',id: 'GS'},
  {text: 'South Sudan'                                 ,  country: 'South Sudan'                                 , iso: 'SS',id: 'SS'},
  {text: 'Spain'                                       ,  country: 'Spain'                                       , iso: 'ES',id: 'ES'},
  {text: 'Sri Lanka'                                   ,  country: 'Sri Lanka'                                   , iso: 'LK',id: 'LK'},
  {text: 'Sudan'                                       ,  country: 'Sudan'                                       , iso: 'SD',id: 'SD'},
  {text: 'Suriname'                                    ,  country: 'Suriname'                                    , iso: 'SR',id: 'SR'},
  {text: 'Svalbard and Jan Mayen'                      ,  country: 'Svalbard and Jan Mayen'                      , iso: 'SJ',id: 'SJ'},
  {text: 'Swaziland'                                   ,  country: 'Swaziland'                                   , iso: 'SZ',id: 'SZ'},
  {text: 'Sweden'                                      ,  country: 'Sweden'                                      , iso: 'SE',id: 'SE'},
  {text: 'Switzerland'                                 ,  country: 'Switzerland'                                 , iso: 'CH',id: 'CH'},
  {text: 'Syrian Arab Republic'                        ,  country: 'Syrian Arab Republic'                        , iso: 'SY',id: 'SY'},
  {text: 'Taiwan, Province of China'                   ,  country: 'Taiwan, Province of China'                   , iso: 'TW',id: 'TW'},
  {text: 'Tajikistan'                                  ,  country: 'Tajikistan'                                  , iso: 'TJ',id: 'TJ'},
  {text: 'Tanzania, United Republic of'                ,  country: 'Tanzania, United Republic of'                , iso: 'TZ',id: 'TZ'},
  {text: 'Thailand'                                    ,  country: 'Thailand'                                    , iso: 'TH',id: 'TH'},
  {text: 'Timor-Leste'                                 ,  country: 'Timor-Leste'                                 , iso: 'TL',id: 'TL'},
  {text: 'Togo'                                        ,  country: 'Togo'                                        , iso: 'TG',id: 'TG'},
  {text: 'Tokelau'                                     ,  country: 'Tokelau'                                     , iso: 'TK',id: 'TK'},
  {text: 'Tonga'                                       ,  country: 'Tonga'                                       , iso: 'TO',id: 'TO'},
  {text: 'Trinidad and Tobago'                         ,  country: 'Trinidad and Tobago'                         , iso: 'TT',id: 'TT'},
  {text: 'Tunisia'                                     ,  country: 'Tunisia'                                     , iso: 'TN',id: 'TN'},
  {text: 'Turkey'                                      ,  country: 'Turkey'                                      , iso: 'TR',id: 'TR'},
  {text: 'Turkmenistan'                                ,  country: 'Turkmenistan'                                , iso: 'TM',id: 'TM'},
  {text: 'Turks and Caicos Islands'                    ,  country: 'Turks and Caicos Islands'                    , iso: 'TC',id: 'TC'},
  {text: 'Tuvalu'                                      ,  country: 'Tuvalu'                                      , iso: 'TV',id: 'TV'},
  {text: 'Uganda'                                      ,  country: 'Uganda'                                      , iso: 'UG',id: 'UG'},
  {text: 'Ukraine'                                     ,  country: 'Ukraine'                                     , iso: 'UA',id: 'UA'},
  {text: 'United Arab Emirates'                        ,  country: 'United Arab Emirates'                        , iso: 'AE',id: 'AE'},
  {text: 'United Kingdom'                              ,  country: 'United Kingdom'                              , iso: 'GB',id: 'GB'},
  {text: 'United States'                               ,  country: 'United States'                               , iso: 'US',id: 'US'},
  {text: 'United States Minor Outlying Islands'        ,  country: 'United States Minor Outlying Islands'        , iso: 'UM',id: 'UM'},
  {text: 'Uruguay'                                     ,  country: 'Uruguay'                                     , iso: 'UY',id: 'UY'},
  {text: 'Uzbekistan'                                  ,  country: 'Uzbekistan'                                  , iso: 'UZ',id: 'UZ'},
  {text: 'Vanuatu'                                     ,  country: 'Vanuatu'                                     , iso: 'VU',id: 'VU'},
  {text: 'Venezuela, Bolivarian Republic of'           ,  country: 'Venezuela, Bolivarian Republic of'           , iso: 'VE',id: 'VE'},
  {text: 'Viet Nam'                                    ,  country: 'Viet Nam'                                    , iso: 'VN',id: 'VN'},
  {text: 'Virgin Islands, British'                     ,  country: 'Virgin Islands, British'                     , iso: 'VG',id: 'VG'},
  {text: 'Virgin Islands, U.S.'                        ,  country: 'Virgin Islands, U.S.'                        , iso: 'VI',id: 'VI'},
  {text: 'Wallis and Futuna'                           ,  country: 'Wallis and Futuna'                           , iso: 'WF',id: 'WF'},
  {text: 'Western Sahara'                              ,  country: 'Western Sahara'                              , iso: 'EH',id: 'EH'},
  {text: 'Yemen'                                       ,  country: 'Yemen'                                       , iso: 'YE',id: 'YE'},
  {text: 'Zambia'                                      ,  country: 'Zambia'                                      , iso: 'ZM',id: 'ZM'},
  {text: 'Zimbabwe'                                    ,  country: 'Zimbabwe'                                    , iso: 'ZW',id: 'ZW'}
]);
}
});
